# **importando libreria numpy**

In [ ]:
import numpy as np

# **creando una lista**


In [ ]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# **lista a arreglo**

In [ ]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## corroborando el tipo de dato del array

In [ ]:
type(arreglo)

numpy.ndarray

In [ ]:
arreglo.dtype

dtype('int64')

# **definiendo el array de int64 a float64**


In [ ]:
np.array(arreglo,dtype=np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# **transformando los datos de int64 a float64**

In [ ]:
arreglo.astype(np.float64)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

<h1>alooooo</h1>
<p>grasias</p>


In [ ]:
nuevoarreglo = np.arange(1,11)
nuevoarreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **arreglo de 2 en 2 con arange**

In [ ]:
nuevoarreglo2 = np.arange(1,11,2)
nuevoarreglo2

array([1, 3, 5, 7, 9])

# funciones locura

## promedio de arreglo

In [ ]:
promedio = np.mean(arreglo)
promedio

5.5

## mediana de arreglo

In [ ]:
mediana = np.median(arreglo)
mediana

5.5

## desviacion estandar de arreglo

In [ ]:
desv_std = np.std(arreglo)
desv_std

2.8722813232690143

# arreglo de solo unos

In [ ]:
arreglo_unos = np.ones(10)
arreglo_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## pasarlo de float a int

In [ ]:
unos_int = arreglo_unos.astype(int)
unos_int

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# funcion random

In [ ]:
array_random = np.random.rand(5)
array_random

array([0.40383769, 0.15410532, 0.07610802, 0.51247531, 0.05757818])

## matriz

In [ ]:
matriz = np.random.rand(3,3)
matriz

array([[0.36340581, 0.07163713, 0.19655513],
       [0.53240127, 0.52735686, 0.93681292],
       [0.56777062, 0.08873734, 0.14886142]])

## arreglo de 10 enteros del 1 al 5

In [ ]:
array_random2 = np.random.randint(1,5,10)
array_random2

array([4, 1, 3, 4, 2, 1, 2, 1, 2, 4])

## matriz de 10 enteros del 1 al 100

In [ ]:
matriz2 = np.random.randint(1,100,(15,15))
matriz2

array([[20, 82, 36, 90, 15, 11, 11, 34, 44, 67, 95, 39, 30, 38, 98],
       [69, 72, 57, 68, 90, 77, 25,  6, 79, 10, 13, 68, 75, 45, 23],
       [93, 89, 52, 13, 70, 84, 19, 25, 34, 66, 14, 47, 72, 11, 50],
       [16, 86, 34, 22, 72, 36, 23, 33, 32, 16, 69, 46, 35, 41, 60],
       [87, 76, 15, 50, 21, 77, 77, 25, 36, 97, 71, 40, 94, 50,  1],
       [73, 72, 26, 70, 92, 87, 38,  6, 59,  9, 64, 54, 37, 22, 25],
       [67, 36, 65, 73, 86, 95, 91, 48, 93, 59, 34, 17, 21, 52, 43],
       [89, 90,  3, 34, 70,  2, 44, 44, 58, 12, 20, 23, 53, 15, 78],
       [55, 49, 12, 70, 40, 84,  4, 19, 94, 13, 16, 31, 46, 57, 94],
       [37, 44,  9, 54, 64, 92, 39, 88, 60, 85, 38, 29, 10, 64, 73],
       [ 3, 66, 15, 24, 57, 74, 74, 86, 36, 71,  5,  5, 94, 37, 62],
       [86, 63, 85, 43, 91, 31, 21,  2, 44, 12, 84, 36, 45, 15, 11],
       [29, 85, 94, 21,  6, 24,  2, 25, 91, 85, 28, 70, 14,  5, 15],
       [76, 48,  2, 58, 35, 63, 59, 67, 23, 45, 95, 19, 71, 23, 86],
       [37, 80, 27, 75, 21, 28, 78